### ISSUE TITLE
Installation via HACS

### ISSUE THREAD

**Issue by Eclipseop** [ZacheryThomas/homeassistant-smartrent#2]
The installation process could be streamlined by adding it via [HACS](https://hacs.xyz/)

https://hacs.xyz/docs/publish/integration is a link to the process of enabling it for their system if you are interested.

**Comment by ZacheryThomas** [comment]
Howdy! I'm trying to weigh the options between trying to move this into [home-assistant/core](https://github.com/home-assistant/core) or going the full HACS route.

Seems like HACS would be less painful to set up development wise, but less intuitive for some users 🤷🏾‍♂️
HA core seems really nice for users since its bundled with every install, but it seems like it would be a pain for me to make a PR and get that through.

I'm open to feedback / suggestions though!

**Comment by Eclipseop** [comment]
I don't know too much about pushing to the core repository, however I would assume that it's a pain to get initially accepted (couldn't be completely wrong for all I know)

Once a user installs hacs they can just add the github repo as a custom integration. As I see it, if someone is comfortable installing home assistant via docker/flashing to rpi/vm/etc, they are more than likely comfortable installing HACS. 

Either way, I'm just happy that this integration exists 🤣

**Comment by ZacheryThomas** [comment]
We made it fam. It's the big leagues.

https://github.com/hacs/default/pull/1226
